### ISSUE TITLE
Data Table doesn't reappear

### ISSUE THREAD

**Issue by raphaelleRC** [SimonbJohnson/rc-cash-3w#10]
When you click on a country in the map the data table appears, but immediately disappears again. 
Clicking on filters directly makes it reappear without re-disappearing.
When clicking on the filters, `cf.whereChart.addFilterHandler` isn't called, so that might be an idea of what's wrong?

**Comment by raphaelleRC** [comment]
After more testing, the filters just don't work when clicking directly in the map, it seems you can only select one country at a time that way, but no filters are actually selected, so everything looks empty.

**Comment by SimonbJohnson** [comment]
I added a restriction of only one country being selected at max last week.  Seems to introduce two bugs...data table not showing when country selected and the current filters text not updating.  I have a feeling I overwrote a filter handler rather than extending it.  Will check tonight.

**Comment by SimonbJohnson** [comment]
Fixed in https://github.com/SimonbJohnson/rc-cash-3w/commit/3da4e9e850579d8b99b812840fd4c0b93c406a43

Let me know if find any others.  Cheers
