### ISSUE TITLE
Map Current Filter always empty

### ISSUE THREAD

**Issue by raphaelleRC** [SimonbJohnson/rc-cash-3w#13]
![screen shot 2018-09-12 at 10 04 03](https://user-images.githubusercontent.com/38655474/45414434-492d4d00-b673-11e8-962d-c60923314ef8.png)

That field is always left empty except for the ",". 
What should be in it?

**Comment by SimonbJohnson** [comment]
Should be fixed in https://github.com/SimonbJohnson/rc-cash-3w/commit/b0de2d1e5a5073596a8fd00fe7d98b77fc53cff9

Second time lucky!

**Comment by raphaelleRC** [comment]
You should change line 151 from:
`html += html+l+", ";`
to
`html = html+l+", ";`

as the string currently increments its previous value (for example: CAN becomes CAN, CAN, USA)
